import type { Metadata } from "next";
import "./globals.css";
import { jost, notoSansJP } from "@/lib/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={`${notoSansJP.variable} ${jost.variable}`}>
      <body>{children}</body>
    </html>
  );
}
